module.exports = {
  camelcase: ['error', { properties: 'never' }],
  'capitalized-comments': 'off',
  'consistent-this': 'off',
  'func-name-matching': 'off',
  'func-names': 2,
  'func-style': 'off',
  'id-blacklist': 'off',
  'id-length': 'off',
  'id-match': 'off',
  'line-comment-position': 'off',
  'lines-between-class-members': 'error',
  'max-depth': 'off',
  'max-lines': 'off',
  'max-lines-per-function': 'off',
  'max-nested-callbacks': 'off',
  'max-params': 'off',
  'max-statements': 'off',
  'max-statements-per-line': 'off',
  'multiline-comment-style': 'off',
  'new-cap': 0,
  'no-array-constructor': 'error',
  'no-bitwise': 'error',
  'no-continue': 'error',
  'no-inline-comments': 'off',
  'no-lonely-if': 0,
  'no-multi-assign': 'error',
  'no-negated-condition': 'off',
  'no-nested-ternary': 0,
  'no-new-object': 'error',
  'no-plusplus': 'error',
  'no-restricted-syntax': 0,
  'no-ternary': 'off',
  'no-underscore-dangle': 'off',
  'no-unneeded-ternary': ['error', { defaultAssignment: false }],
  'one-var': ['error', 'never'],
  'operator-assignment': ['error', 'always'],
  'padding-line-between-statements': 'off',
  'prefer-object-spread': 'error',
  'sort-keys': 'off',
  'sort-vars': 'off',
  'spaced-comment': 'off',
};
